## get invites of a user
GET http://localhost:4000/invites/romeo/invited

### get event OK
GET http://localhost:4000/events/0de0a518-b45d-430d-b11d-4ed91ef4cf08
content-type: application/json


### get event KO
GET http://localhost:4000/events/1
content-type: application/json

### delete event
DELETE http://localhost:4000/events/antony/delete
content-type: application/json

{
    "id":"7db98688-20dd-47c1-a8b7-cde12a9279fa"
}

### get all events
GET http://localhost:4000/events/


    // "statut":"private",
    //"category":"Festival"
    //does not consider change with those two for now
    //TO DO
### update event
PUT http://localhost:4000/events/9d09cdbb-3d13-4c57-b2ca-8d43d9483a3c/update
content-type: application/json

{
    "name":"modifiedEvent",
    "starting_date":"15-12-2022",
    "ending_date":"25-12-2022",
    "description":"modifiedDescription",
    "username":"antony"
    

}
    

### get all events participating
GET  http://localhost:4000/events/register/juliette

### create event
POST http://localhost:4000/events/create
content-type: application/json

{
    "name":"Birthday party",
    "starting_date":"15-12-2022",
    "ending_date":"25-12-2022",
    "creation_date":"15-12-2022",
    "description":"description",
    "username":"antony",
    "statut":"private"

}

### participate to an event
PUT http://localhost:4000/events/9d09cdbb-3d13-4c57-b2ca-8d43d9483a3c/participate
content-type: application/json

{    
    "username":"yseut" 
}


### get all events by category
GET http://localhost:4000/events/categories/Festival





### unparticipate to an event
PUT http://localhost:4000/events/9d09cdbb-3d13-4c57-b2ca-8d43d9483a3c/unparticipate
content-type: application/json

{    
    "username":"juliette" 
}

    