### get de base --> juste le hello world
GET http://localhost:4000/

### Login
POST http://localhost:4000/auth/login
content-type: application/json

{
    "username":"test",
    "password":"test"
}

### Register
POST http://localhost:4000/auth/register 
content-type: application/json

{
    "username":"test",
    "name":"loulou",
    "firstname":"lolo",
    "email":"louloulesgrlolo@mail.com",
    "password":"test"
}
    

