### get de base --> juste le hello world
GET http://localhost:4000/

### Login
POST http://localhost:4000/auth/login
content-type: application/json

{
    "username":"testazkqeliuopmpe23242",
    "password":"mdp"
}

### Register
POST http://localhost:4000/auth/register 
content-type: application/json

{
    "username":"testazkqeliuopmpe23242",
    "password":"mdp",
    "email": "test12az78@test.com"
}

